### PR TITLE
test: add testFutureRounds helper

### PR DESCRIPTION
**Pull request by Xiphe**
<a href="https://teamsgame.agilepainrelief.com/preview/test-future-rounds">published to gh-pages</a><hr />

while playing round with our idea of a `testRoundChange` helper I figured that it feels less magic if we re-use the [`AppState['currentRound']` type](https://github.com/mlevison/high-performance-teams-game/blob/main/src/state/useAppState.ts#L30-L45)  as input instead of inventing another format for the same data.

That required a few helpers so that jest correctly compares the partial input with the current state but looking at round1.spec i like it really much.

what do you think?

### CODE REVIEW

**Comment by mlevison** [comment]
I don't quite understand Deep Partial. It clearly works.

FWIW I was going to simplify so that all tests needed to declare both capacity and chance.

**Comment by Xiphe** [comment]
There is a build-in `Partial` in typescript
```ts
type T = { a: string; b: number };
type PT = Partial<T>; // { a?: string; b?; number }
```

But it only works on the first layer. So if you want to have everything optional deep partial helps

```ts
type T = { a: string; b: number, c: { deep: true } };
type PT = Partial<T>; // { a?: string; b?; number, c?: { deep: true } }
// note that "deep" does not have a "?" here
type DPT = DeepPartial<T>; // { a?: string; b?; number, c?: { deep?: true } }
```

**Comment by mlevison** [comment]
Ok this makes a bit more sense. Followup - if all of the tests had both Capacity and Chance would the Partial be required at all?

**Comment by Xiphe** [comment]
Yes, because `testCurrentRound` and `testFutureRounds` helpers both are able to compare on the full `AppState['currentRound']` type.

For example here:  https://github.com/mlevison/high-performance-teams-game/blob/main/src/config/rounds/round1.spec.tsx#L20-L30

As mentioned we could also use a helper like you've designed that accepts totalCapacity and userStoryChance but as i've stated [in the description of this issue](https://github.com/mlevison/high-performance-teams-game/pull/82#issue-539429026) 

>  I figured that it feels less magic if we re-use the [`AppState['currentRound']` type](https://github.com/mlevison/high-performance-teams-game/blob/main/src/state/useAppState.ts#L30-L45)  as input instead of inventing another format for the same data.

**Comment by mlevison** [comment]
I think my original intention got lost here.

My intention was for testCurrentRound to have two statements:
```
expect(game.state.currentRound.userStoryChance).toEqual(
      chanceChange + START_USER_STORY_CHANCE,
    );
expect(game.state.currentRound.capacity.total).toEqual(capacity);
```

I intended to eliminate testFutureCapacities() and testUserStoryChance(). The intention is that all testFutureRounds would always be expected to pass in the futureCapacity and userStoryChance**Change** in. The requirement to always test both was to make intentions clear.

The reason for passing in the userStoryChance**Change**  is that don't care about the final percentage instead what affect that had.

When this refactoring was finished, it was intended to be easy to tweak the base percentage for START_USER_STORY_CHANCE because no test would rely on it.

When I try to write the code for this

`export function testCurrentRound(
  game: ReturnType<typeof getGame>,
  round: DeepPartial<AppState['currentRound']>,
) {
  expect(game.state.currentRound.userStoryChance).toEqual(round.userStoryChance + START_USER_STORY_CHANCE);
  expect(game.state.currentRound.capacity.total).toEqual(round.capacity);
}`

I get a compilation error, saying round.userStoryChance is undefined.

I will admit to being a little frazzled. I'm trying to write refactor code in a programming language I don't quite understand. At least with a statically typed language the compiler would yell at me until I understood.

**Comment by Xiphe** [comment]
> I think my original intention got lost here.

I agree, thought it would be helpful. Sorry for over-engineering.

> I intended to eliminate testFutureCapacities() and testUserStoryChance(). The intention is that all testFutureRounds would always be expected to pass in the futureCapacity and userStoryChanceChange in. The requirement to always test both was to make intentions clear.

If you still want to keep my helpers you could implement this as a higher layer like `testFutureRounds`

> The reason for passing in the userStoryChanceChange is that don't care about the final percentage instead what affect that had.
> When this refactoring was finished, it was intended to be easy to tweak the base percentage for START_USER_STORY_CHANCE because no test would rely on it.

I understand. I personally would make the test independent from this by explicitly overwriting round1 in the rounds mock because this is bringing the precondition (explicitly currently). 
For example in `round2.spec.ts`

```ts
jest.mock('./index', () => ({
  rounds: {
    1: {
      ...require('./round1').round1,
      effect: () => [
        {
          title: EFFECT_HIDDEN,
          capacityChange: 10,
        },
        {
          title: EFFECT_HIDDEN,
          userStoryChange: 30,
        },
      ],
    },
    2: require('./round2').round2,
  },
}));
```

Concerning your typescript warnings:

```ts
export function testCurrentRound(
  game: ReturnType<typeof getGame>,
  round: DeepPartial<AppState['currentRound']>,
) {
  /* round.userStoryChance is possibly undefined here because round is typed as a deep partial
     you could either change the signature of the function back to what you've originally intended or 
     write round.userStoryChance || 0 + START_USER_STORY_CHANCE */
  expect(game.state.currentRound.userStoryChance).toEqual(round.userStoryChance + START_USER_STORY_CHANCE);
  /* Here you're comparing the current rounds total capacity to the capacity object 
     (which has `total` and `available` as props) this will never succeed.
     You will face a similar problem when accessing the total prop because capacity might be undefined
     If you want to keep the method signature I'd suggest round.capacity?.total */
  expect(game.state.currentRound.capacity.total).toEqual(round.capacity);
}
```

I hope this helps. If you like I could also just revert the my changes so you can continue with you original intention.

**Pull request merged**
